### ISSUE TITLE
Add ability to fetch a bug's attachments

### ISSUE THREAD

**Issue by KWierso** [AutomatedTester/Bugsy#35] opened 2015-12-12 01:45 UTC
I don't need this at the moment, but it would be nice to have the ability to fetch a list of attachments for a bug, and then get/set information about those attachments, like reviews or feedback flags, maybe be able to obsolete an attachment. Stretch goal of attaching an attachment to a bug, I guess.

**Comment by AutomatedTester** [comment] 2016-03-31 13:02
Closing this as a duplicate of issue #42 as its all in the same area

**Closed by AutomatedTester** 2016-03-31 13:02 UTC
